# Generated by Django 2.1.8 on 2019-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorite_genres',
            field=models.ManyToManyField(related_name='genrestouser', to='movies.Genre'),
        ),
    ]
