# Generated by Django 2.1.8 on 2019-05-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190515_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
