# Generated by Django 2.1.8 on 2019-05-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190516_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='content',
            field=models.TextField(),
        ),
    ]
