# Generated by Django 2.1.8 on 2019-05-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190516_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
